name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Check default main state - generated files for postgresql-operator
        run: |
          make render-postgresql-operator-catalog
          echo "Checking there is no source code changes"
          git diff --exit-code

      - name: Check default main state - generated files for pxc-operator
        run: |
          make render-pxc-operator-catalog
          echo "Checking there is no source code changes"
          git diff --exit-code

      - name: Check default main state - generated files for psmdb-operator
        run: |
          make render-psmdb-operator-catalog
          echo "Checking there is no source code changes"
          git diff --exit-code

      - name: Build image to check it for vulnerabilities
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          push: false
          tags: "perconalab/everest-catalog:0.0.0"
          file: everest-catalog.Dockerfile

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env
          pwd
          git status
